### ISSUE TITLE
Hydra::Derivatives::Processors::Document #convert_to_format possible bug

### ISSUE THREAD

**Issue by geekscruff** [samvera/hydra-derivatives#196]
In a local hyrax I added in some logic to `app/services/hyrax/file_set_derivatives_service.rb` to generate a pdf 'service-file' for office documents following the same pattern as used for thumbnails. 

When this runs I get errors which I have pinned down to the following line in [lib/hydra/derivatives/processors/document.rb](https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/processors/document.rb#L26)

If I take out the `File.read()`, then everything works:
```
output_file_service.call(converted_file, directives)
```
Is this a bug ... I don't know enough about hydra-derivatives to know whether there are places where the File.read part would be necessary?

**Comment by jrochkind** [comment]
Can you add details on the errors you get, copy-paste of the exception class and stack trace if it's an exception raised you're getting?

**Comment by geekscruff** [comment]
@jrochkind originally it was `ArgumentError (string contains null byte)`. 

I messed around for a long time thinking it was encoding problems, but then realised that switching to passing the filename instead of the file contents fixed the problem.

**Comment by cjcolvar** [comment]
I think the difference is in the expected parameters of the output file service.  In hydra-derivatives the default output service appears to be Hydra::Derivatives::PersistBasicContainedOutputFileService which is expecting an IO or String object:
https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/services/persist_basic_contained_output_file_service.rb#L12
While for Hyrax the output file service is Hyrax::PersistDerivatives which expects something that responds to `#read`:
https://github.com/samvera/hyrax/blob/master/app/services/hyrax/persist_derivatives.rb#L8

**Comment by geekscruff** [comment]
Ah, thanks Chris, that makes sense, so my local hack is the way to go for this. I'll close this issue.
