### ISSUE TITLE
Fix CI Build

### ISSUE THREAD

**Issue by tpendragon** [samvera/hydra-derivatives#202]
CI is broken because Kakadu download is gone.

**Comment by jrgriffiniii** [comment]
I believe that this might become a blocking issue, @pulibrary contacted the parties responsible for hosting the download, and a notification was given that the site was undergoing an upgrade (without a timeline for this).

**Comment by jenlindner** [comment]
Ugh. Well, an upgrade isn't necessarily a blocker, it could just be
temporarily unavailable. If people would like, I could take responsibility
for keeping in contact with them about its availibility - if in a week or
so it's still not back, we could discuss our options further then.

Jen

**Comment by jrgriffiniii** [comment]
Blocks https://github.com/samvera/maintenance/issues/17

**Comment by cjcolvar** [comment]
Build is working again.  See #203.
