### ISSUE TITLE
Hydra::Derivatives::Processors::Jpeg2kImage.level_count_for_size can return -1

### ISSUE THREAD

**Issue by aploshay** [samvera/hydra-derivatives#217]
I got stuck on this for awhile when I chose a small image as a test case:
kdu_compress aborts and core dumps if you pass in a negative Clevels value, but [level_count_for_size returns -1 for images 95x95 or smaller](https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/processors/jpeg2k_image.rb#L52-L60).  Changing the return value from:
```ruby
levels - 1
```
to:
```ruby
[levels - 1, 0].max
```
or something equivalent would catch this.  Is this an appropriate change?

**Comment by jenlindner** [comment]
Well, it seems ilke 95 * 95 is a requirement, so perhaps a better way of
expressing that would be to explicitly use True if an image is at least
that. Any interest in making a PR for it?

Jennifer

**Comment by aploshay** [comment]
@jenlindner Sure, I'll put up a PR

**Comment by aploshay** [comment]
@jenlindner PR is up as #219
