### ISSUE TITLE
"gray" vs "grey" breaking default jp2k recipe lookup?

### ISSUE THREAD

**Issue by aploshay** [samvera/hydra-derivatives#218]
The two default jp2k recipe lookups are [:default_color](https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/config.rb#L46) and [:default_grey](https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/config.rb#L60) (with an e), but the [`quality` value](https://github.com/samvera/hydra-derivatives/blob/master/lib/hydra/derivatives/processors/jpeg2k_image.rb#L89) passed to `kdu_compress_recipe`, `calculate_recipe` can have a value of 'color' (which matches fine) or 'gray' (with an a) (which doesn't match).  I don't want to take a stance on a "color" vs "colour" or "gray" vs "grey" debate, in _general_, but in this case presumably we we should make the recipe key `:default_gray` (with an a) to match the MiniMagick output, since looking up `:default_grey` isn't returning a value, currently?

**Comment by aploshay** [comment]
PR is up as #220

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-derivatives/pull/220 resolved this issue.
